spring:
  application:
    name: crud

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:file:.env[.properties]

